// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuqNW8vGW0i2Cf04HxsuZK7mGMdzD9Pwg',
    appId: '1:531459620591:web:b210ce3d945d28020de51a',
    messagingSenderId: '531459620591',
    projectId: 'buddy-guardian',
    authDomain: 'buddy-guardian.firebaseapp.com',
    storageBucket: 'buddy-guardian.appspot.com',
    measurementId: 'G-XF7XJ4PPE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN69_27ZvN-YtgtIy5jUO-tO8MrCC-7hI',
    appId: '1:531459620591:android:ce536b7c64aca6aa0de51a',
    messagingSenderId: '531459620591',
    projectId: 'buddy-guardian',
    storageBucket: 'buddy-guardian.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgWEf_Ef5aad1wSqQSuFRNZieK_IfbzsA',
    appId: '1:531459620591:ios:c0adda9a1a4c57e40de51a',
    messagingSenderId: '531459620591',
    projectId: 'buddy-guardian',
    storageBucket: 'buddy-guardian.appspot.com',
    iosClientId: '531459620591-04hfgil0tq2c0iojp3gcko78epcb63od.apps.googleusercontent.com',
    iosBundleId: 'com.example.buddyGuardian',
  );
}
